const sitesData = [
    {
        id: 1,
        name: "Willow Creek Ag Lab",
        location: "Modesto, CA",
        pricePerDay: 850,
        industry: "agtech",
        services: ["Tractor", "Operator", "Soil Lab", "Irrigation Tech"],
        image: "https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=400&h=300&auto=format&fit=crop",
        description: "State-of-the-art agricultural testing facility with comprehensive soil analysis capabilities.",
        features: ["24/7 Access", "Climate Controlled", "Data Collection", "Expert Support"],
        rating: 4.8,
        reviews: 24
    },
    {
        id: 2,
        name: "Blue Horizon Farms",
        location: "Ames, IA",
        pricePerDay: 720,
        industry: "agtech",
        services: ["Tractor", "Drone Access", "Local Agronomist"],
        image: "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=400&h=300&auto=format&fit=crop",
        description: "Expansive farmland perfect for large-scale agricultural technology testing.",
        features: ["Drone Friendly", "Expert Guidance", "Multiple Plots", "Weather Station"],
        rating: 4.6,
        reviews: 18
    },
    {
        id: 3,
        name: "Pine Ridge Ag Station",
        location: "Bozeman, MT",
        pricePerDay: 680,
        industry: "agtech",
        services: ["Livestock", "Fencing", "Data Collection"],
        image: "https://images.unsplash.com/photo-1500937386664-56d1dfef3854?w=400&h=300&auto=format&fit=crop",
        description: "Mountain agricultural station specializing in livestock and pasture management research.",
        features: ["Livestock Access", "Mountain Climate", "Research Facilities", "Safety Equipment"],
        rating: 4.7,
        reviews: 12
    },
    {
        id: 4,
        name: "TerraNova Research Plot",
        location: "Salinas, CA",
        pricePerDay: 1100,
        industry: "agtech",
        services: ["Sensor Grid", "Precision Irrigation", "Crop Consultant"],
        image: "https://images.unsplash.com/photo-1592982117638-fb1c4e6b9d10?w=400&h=300&auto=format&fit=crop",
        description: "Premium research facility with advanced sensor networks and precision agriculture tools.",
        features: ["Sensor Network", "Precision Tools", "Expert Consultants", "Data Analytics"],
        rating: 4.9,
        reviews: 31
    },
    {
        id: 5,
        name: "High Ridge Ranch",
        location: "Lubbock, TX",
        pricePerDay: 550,
        industry: "mobility",
        services: ["Heavy Machinery", "Dust Control", "Drone Clearance"],
        image: "https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=400&h=300&auto=format&fit=crop",
        description: "Large open terrain ideal for mobility and robotics testing in challenging conditions.",
        features: ["Open Terrain", "Heavy Equipment", "Dust Testing", "Clear Airspace"],
        rating: 4.4,
        reviews: 15
    },
    {
        id: 6,
        name: "Echo Valley Co-op",
        location: "Athens, GA",
        pricePerDay: 460,
        industry: "agtech",
        services: ["Tractors", "Operator", "Access to Students"],
        image: "https://images.unsplash.com/photo-1472214103451-9374bd1c798e?w=400&h=300&auto=format&fit=crop",
        description: "University-affiliated testing ground with access to research students and equipment.",
        features: ["University Access", "Student Support", "Research Facilities", "Academic Network"],
        rating: 4.5,
        reviews: 22
    },
    {
        id: 7,
        name: "Dakota Plains Test Site",
        location: "Fargo, ND",
        pricePerDay: 610,
        industry: "robotics",
        services: ["Autonomous Tractor Access", "Winter Trials"],
        image: "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=400&h=300&auto=format&fit=crop",
        description: "Specialized facility for autonomous vehicle testing with extreme weather capabilities.",
        features: ["Autonomous Testing", "Winter Conditions", "GPS Systems", "Safety Protocols"],
        rating: 4.6,
        reviews: 9
    },
    {
        id: 8,
        name: "Liberty Ag Commons",
        location: "Lincoln, NE",
        pricePerDay: 490,
        industry: "agtech",
        services: ["Seeder", "Real-Time Weather Feed"],
        image: "https://images.unsplash.com/photo-1560493676-04071c5f467b?w=400&h=300&auto=format&fit=crop",
        description: "Community agricultural space with modern seeding equipment and weather monitoring.",
        features: ["Weather Station", "Seeding Equipment", "Community Support", "Data Sharing"],
        rating: 4.3,
        reviews: 16
    },
    {
        id: 9,
        name: "Redwood AgTech Field",
        location: "Eugene, OR",
        pricePerDay: 875,
        industry: "agtech",
        services: ["Indoor/Outdoor Plots", "Sensor Suite"],
        image: "https://images.unsplash.com/photo-1530836369250-ef72a3f5cda8?w=400&h=300&auto=format&fit=crop",
        description: "Hybrid indoor-outdoor facility perfect for controlled agricultural experiments.",
        features: ["Indoor/Outdoor", "Climate Control", "Advanced Sensors", "Flexible Layouts"],
        rating: 4.8,
        reviews: 27
    },
    {
        id: 10,
        name: "Clearwater Trials",
        location: "Gainesville, FL",
        pricePerDay: 500,
        industry: "climate",
        services: ["Aquaponics Tanks", "Greenhouse", "Lab Access"],
        image: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=400&h=300&auto=format&fit=crop",
        description: "Aquaponics and climate technology testing facility with greenhouse capabilities.",
        features: ["Aquaponics", "Greenhouse", "Lab Facilities", "Climate Testing"],
        rating: 4.7,
        reviews: 19
    },
    {
        id: 11,
        name: "Prairie Edge Robotics Zone",
        location: "Norman, OK",
        pricePerDay: 660,
        industry: "robotics",
        services: ["GPS Grid", "Open Field for Drones"],
        image: "https://images.unsplash.com/photo-1518709268805-4e9042af2176?w=400&h=300&auto=format&fit=crop",
        description: "Dedicated robotics testing zone with precise GPS grid and drone flight areas.",
        features: ["GPS Grid", "Drone Testing", "Open Space", "Navigation Systems"],
        rating: 4.5,
        reviews: 13
    },
    {
        id: 12,
        name: "Rockwell Agrostation",
        location: "Davis, CA",
        pricePerDay: 900,
        industry: "agtech",
        services: ["24/7 Monitoring", "Research Assistants"],
        image: "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=400&h=300&auto=format&fit=crop",
        description: "Premium agricultural research station with round-the-clock monitoring and expert support.",
        features: ["24/7 Support", "Research Staff", "Monitoring Systems", "Premium Service"],
        rating: 4.9,
        reviews: 35
    },
    {
        id: 13,
        name: "Mesa Dryland Trials",
        location: "Tucson, AZ",
        pricePerDay: 440,
        industry: "climate",
        services: ["Irrigation Systems", "Drought-Tolerant Crops"],
        image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400&h=300&auto=format&fit=crop",
        description: "Desert testing facility specializing in drought-resistant agriculture and water conservation.",
        features: ["Desert Climate", "Water Conservation", "Drought Testing", "Solar Access"],
        rating: 4.4,
        reviews: 11
    },
    {
        id: 14,
        name: "Hudson River Microfarm",
        location: "Hudson Valley, NY",
        pricePerDay: 725,
        industry: "agtech",
        services: ["Urban Farm Tech", "Vertical Racks"],
        image: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=400&h=300&auto=format&fit=crop",
        description: "Urban microfarm facility with vertical growing systems and city-scale testing capabilities.",
        features: ["Urban Setting", "Vertical Farming", "Space Efficient", "Tech Integration"],
        rating: 4.6,
        reviews: 20
    },
    {
        id: 15,
        name: "Bear Creek Ag Station",
        location: "Des Moines, IA",
        pricePerDay: 530,
        industry: "agtech",
        services: ["Tractor", "Operator", "Planting Assistance"],
        image: "https://images.unsplash.com/photo-1464226184884-fa280b87c399?w=400&h=300&auto=format&fit=crop",
        description: "Traditional agricultural facility with experienced operators and planting support.",
        features: ["Experienced Staff", "Traditional Methods", "Hands-on Support", "Flexible Timing"],
        rating: 4.3,
        reviews: 14
    },
    {
        id: 16,
        name: "Cornfield Alpha",
        location: "Iowa City, IA",
        pricePerDay: 550,
        industry: "agtech",
        services: ["Tractor", "Operator", "Crop Lab", "Irrigation System"],
        image: "https://images.unsplash.com/photo-1572635148818-ef6fd45eb394?w=400&h=300&auto=format&fit=crop",
        description: "Advanced agricultural testing facility with comprehensive crop analysis and irrigation capabilities.",
        features: ["Crop Lab", "Irrigation Systems", "Expert Support", "Data Collection"],
        rating: 4.5,
        reviews: 18
    },
    {
        id: 17,
        name: "Sunny Farm Trials",
        location: "Fresno, CA",
        pricePerDay: 600,
        industry: "agtech",
        services: ["Drone Access", "Local Agronomist", "Weather Station"],
        image: "https://images.unsplash.com/photo-1500937386664-56d1dfef3854?w=400&h=300&auto=format&fit=crop",
        description: "Sunny agricultural facility perfect for crop testing with drone capabilities and weather monitoring.",
        features: ["Drone Friendly", "Weather Monitoring", "Expert Guidance", "Sunny Climate"],
        rating: 4.6,
        reviews: 22
    },
    {
        id: 18,
        name: "Green Valley Ranch",
        location: "Madison, WI",
        pricePerDay: 520,
        industry: "agtech",
        services: ["Tractor", "Operator", "Pest Monitoring", "IoT Sensors"],
        image: "https://images.unsplash.com/photo-1493804714600-6edb1cd93080?w=400&h=300&auto=format&fit=crop",
        description: "Modern ranch facility with integrated IoT sensors and pest monitoring systems.",
        features: ["IoT Integration", "Pest Control", "Smart Sensors", "Experienced Staff"],
        rating: 4.4,
        reviews: 16
    },
    {
        id: 19,
        name: "Delta Soil Lab",
        location: "Greenville, MS",
        pricePerDay: 480,
        industry: "agtech",
        services: ["Soil Testing", "Drone Imaging", "Irrigation"],
        image: "https://images.unsplash.com/photo-1601131690183-c238e4b4bb2c?w=400&h=300&auto=format&fit=crop",
        description: "Delta region facility specializing in soil analysis with drone imaging capabilities.",
        features: ["Soil Analysis", "Drone Technology", "Delta Climate", "Irrigation Access"],
        rating: 4.3,
        reviews: 13
    },
    {
        id: 20,
        name: "Rocky Plains",
        location: "Fort Collins, CO",
        pricePerDay: 500,
        industry: "agtech",
        services: ["Elevation Testing", "Crop Rotation", "Local Experts"],
        image: "https://images.unsplash.com/photo-1464226184884-fa280b87c399?w=400&h=300&auto=format&fit=crop",
        description: "High-altitude agricultural testing facility perfect for elevation-specific crop research.",
        features: ["High Altitude", "Crop Rotation", "Local Expertise", "Mountain Climate"],
        rating: 4.7,
        reviews: 11
    },
    {
        id: 21,
        name: "Harvest Grove",
        location: "Salem, OR",
        pricePerDay: 510,
        industry: "agtech",
        services: ["Operator", "Irrigation", "Fruit Crop Access"],
        image: "https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=400&h=300&auto=format&fit=crop",
        description: "Orchard facility specializing in fruit crop testing with expert operators.",
        features: ["Fruit Crops", "Orchard Setting", "Irrigation Systems", "Expert Operators"],
        rating: 4.5,
        reviews: 19
    },
    {
        id: 22,
        name: "Flatland Fields",
        location: "Lubbock, TX",
        pricePerDay: 530,
        industry: "agtech",
        services: ["Tractor", "Weather Station", "Soil Analysis"],
        image: "https://images.unsplash.com/photo-1523348837708-15d4a09cfac2?w=400&h=300&auto=format&fit=crop",
        description: "Open flatland facility with comprehensive weather monitoring and soil analysis.",
        features: ["Open Terrain", "Weather Station", "Soil Testing", "Flat Geography"],
        rating: 4.4,
        reviews: 15
    },
    {
        id: 23,
        name: "Everglade Farm Test",
        location: "Gainesville, FL",
        pricePerDay: 570,
        industry: "agtech",
        services: ["Wet Soil Trials", "Pest Testing", "Agronomist"],
        image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=300&auto=format&fit=crop",
        description: "Subtropical testing facility specializing in wet soil conditions and pest management.",
        features: ["Wet Soil Testing", "Pest Management", "Subtropical Climate", "Expert Support"],
        rating: 4.6,
        reviews: 17
    },
    {
        id: 24,
        name: "Maple Leaf Acres",
        location: "Burlington, VT",
        pricePerDay: 490,
        industry: "agtech",
        services: ["Cold Climate Crops", "Tractor", "Lab"],
        image: "https://images.unsplash.com/photo-1551632811-561732d1e306?w=400&h=300&auto=format&fit=crop",
        description: "Northern climate facility perfect for cold-weather crop testing and research.",
        features: ["Cold Climate", "Lab Access", "Winter Testing", "Specialized Crops"],
        rating: 4.3,
        reviews: 12
    },
    {
        id: 25,
        name: "Canyon Ridge Trials",
        location: "Tucson, AZ",
        pricePerDay: 610,
        industry: "agtech",
        services: ["Desert Crops", "Irrigation", "Expert Support"],
        image: "https://images.unsplash.com/photo-1490810194309-344b3661ba39?w=400&h=300&auto=format&fit=crop",
        description: "Desert canyon facility specializing in arid climate crop research and water management.",
        features: ["Desert Climate", "Water Conservation", "Canyon Setting", "Expert Guidance"],
        rating: 4.5,
        reviews: 14
    },
    {
        id: 26,
        name: "Sunrise Plant Lab",
        location: "Yuma, AZ",
        pricePerDay: 560,
        industry: "agtech",
        services: ["Greenhouse Access", "Irrigation", "Crop Sensor"],
        image: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=400&h=300&auto=format&fit=crop",
        description: "Advanced plant laboratory with greenhouse facilities and sensor technology.",
        features: ["Greenhouse", "Sensor Technology", "Controlled Environment", "Plant Research"],
        rating: 4.7,
        reviews: 21
    },
    {
        id: 27,
        name: "Wheatstone Range",
        location: "Lincoln, NE",
        pricePerDay: 500,
        industry: "agtech",
        services: ["Wheat Testing", "Machinery", "Local Support"],
        image: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=400&h=300&auto=format&fit=crop",
        description: "Dedicated wheat testing facility with specialized machinery and local expertise.",
        features: ["Wheat Specialization", "Farm Machinery", "Local Expertise", "Plains Setting"],
        rating: 4.4,
        reviews: 16
    },
    {
        id: 28,
        name: "Golden Prairie Testbed",
        location: "Topeka, KS",
        pricePerDay: 520,
        industry: "agtech",
        services: ["Open Field", "Sensor Rig", "Machinery"],
        image: "https://images.unsplash.com/photo-1523741543316-beb7fc7023d8?w=400&h=300&auto=format&fit=crop",
        description: "Open prairie testing ground with advanced sensor systems and agricultural machinery.",
        features: ["Open Prairie", "Sensor Systems", "Agricultural Machinery", "Wide Open Space"],
        rating: 4.6,
        reviews: 18
    },
    {
        id: 29,
        name: "Silicon Crops",
        location: "Palo Alto, CA",
        pricePerDay: 580,
        industry: "agtech",
        services: ["Precision Ag Tools", "Sensor Testing", "Drone Hub"],
        image: "https://images.unsplash.com/photo-1581092160562-40aa08e78837?w=400&h=300&auto=format&fit=crop",
        description: "High-tech agricultural facility in Silicon Valley with cutting-edge precision agriculture tools.",
        features: ["Precision Technology", "Drone Operations", "Tech Integration", "Innovation Hub"],
        rating: 4.8,
        reviews: 25
    },
    {
        id: 30,
        name: "River Delta Acres",
        location: "Sacramento, CA",
        pricePerDay: 540,
        industry: "agtech",
        services: ["Irrigation Canal", "Tractor", "Soil Monitoring"],
        image: "https://images.unsplash.com/photo-1495107334309-fcf20504a5ab?w=400&h=300&auto=format&fit=crop",
        description: "Delta region facility with canal irrigation systems and comprehensive soil monitoring.",
        features: ["Canal Irrigation", "Delta Soil", "Water Management", "Soil Monitoring"],
        rating: 4.5,
        reviews: 20
    },
    {
        id: 31,
        name: "Desert Road Proving Ground",
        location: "Barstow, CA",
        pricePerDay: 950,
        industry: "mobility",
        services: ["Off-road testing", "High-temp conditions", "Autonomous Vehicle Track"],
        image: "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=400&h=300&auto=format&fit=crop",
        description: "Extreme desert testing facility for off-road and autonomous vehicle development in high-temperature conditions.",
        features: ["Off-road Terrain", "High Temperature", "Autonomous Testing", "Desert Conditions"],
        rating: 4.7,
        reviews: 23
    },
    {
        id: 32,
        name: "Metro Mobility Loop",
        location: "Detroit, MI",
        pricePerDay: 880,
        industry: "mobility",
        services: ["Urban traffic simulation", "Sensor Grid", "Charging Infrastructure"],
        image: "https://images.unsplash.com/photo-1519501025264-65ba15a82390?w=400&h=300&auto=format&fit=crop",
        description: "Urban mobility testing facility with traffic simulation and EV charging infrastructure.",
        features: ["Urban Environment", "Traffic Simulation", "EV Charging", "Sensor Network"],
        rating: 4.6,
        reviews: 19
    },
    {
        id: 33,
        name: "Rust Belt Mobility Field",
        location: "Cleveland, OH",
        pricePerDay: 790,
        industry: "mobility",
        services: ["EV Charging Network", "Rough Terrain", "Traffic Simulation"],
        image: "https://images.unsplash.com/photo-1530457971375-38f0b22e0c40?w=400&h=300&auto=format&fit=crop",
        description: "Industrial mobility testing facility with challenging terrain and comprehensive EV infrastructure.",
        features: ["Industrial Setting", "Rough Terrain", "EV Infrastructure", "Traffic Testing"],
        rating: 4.4,
        reviews: 15
    },
    {
        id: 34,
        name: "Coastal Highway Strip",
        location: "Charleston, SC",
        pricePerDay: 730,
        industry: "mobility",
        services: ["Salt Exposure", "Long-Range Highway Testing"],
        image: "https://images.unsplash.com/photo-1449824913935-59a10b8d2000?w=400&h=300&auto=format&fit=crop",
        description: "Coastal testing facility for long-range highway testing with salt exposure conditions.",
        features: ["Coastal Environment", "Salt Exposure", "Highway Testing", "Long Range"],
        rating: 4.5,
        reviews: 17
    },
    {
        id: 35,
        name: "Midwest Logistics Hub",
        location: "Indianapolis, IN",
        pricePerDay: 810,
        industry: "mobility",
        services: ["Heavy Truck Access", "Depot Simulation", "Loading Equipment"],
        image: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=400&h=300&auto=format&fit=crop",
        description: "Logistics testing facility with heavy truck access and depot simulation capabilities.",
        features: ["Heavy Truck Testing", "Logistics Simulation", "Loading Equipment", "Depot Access"],
        rating: 4.6,
        reviews: 21
    },
    {
        id: 36,
        name: "Evergreen Auto Track",
        location: "Tacoma, WA",
        pricePerDay: 920,
        industry: "mobility",
        services: ["Rain Exposure", "Autonomous Navigation", "EV Test Zone"],
        image: "https://images.unsplash.com/photo-1473773508845-188df298d2d1?w=400&h=300&auto=format&fit=crop",
        description: "Pacific Northwest testing facility specializing in wet weather autonomous vehicle testing.",
        features: ["Rain Testing", "Autonomous Systems", "EV Testing", "Wet Conditions"],
        rating: 4.7,
        reviews: 24
    }
    ];