const sitesData = [
    {
        id: 1,
        name: "Willow Creek Ag Lab",
        location: "Modesto, CA",
        pricePerDay: 850,
        industry: "agtech",
        services: ["Tractor", "Operator", "Soil Lab", "Irrigation Tech"],
        image: "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=400&h=300&auto=format&fit=crop",
        description: "State-of-the-art agricultural testing facility with comprehensive soil analysis capabilities.",
        features: ["24/7 Access", "Climate Controlled", "Data Collection", "Expert Support"],
        rating: 4.8,
        reviews: 24
    },
    {
        id: 2,
        name: "Blue Horizon Farms",
        location: "Ames, IA",
        pricePerDay: 720,
        industry: "agtech",
        services: ["Tractor", "Drone Access", "Local Agronomist"],
        image: "https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=400&h=300&auto=format&fit=crop",
        description: "Expansive farmland perfect for large-scale agricultural technology testing.",
        features: ["Drone Friendly", "Expert Guidance", "Multiple Plots", "Weather Station"],
        rating: 4.6,
        reviews: 18
    },
    {
        id: 3,
        name: "Pine Ridge Ag Station",
        location: "Bozeman, MT",
        pricePerDay: 680,
        industry: "agtech",
        services: ["Livestock", "Fencing", "Data Collection"],
        image: "https://images.unsplash.com/photo-1500937386664-56d1dfef3854?w=400&h=300&auto=format&fit=crop",
        description: "Mountain agricultural station specializing in livestock and pasture management research.",
        features: ["Livestock Access", "Mountain Climate", "Research Facilities", "Safety Equipment"],
        rating: 4.7,
        reviews: 12
    },
    {
        id: 4,
        name: "TerraNova Research Plot",
        location: "Salinas, CA",
        pricePerDay: 1100,
        industry: "agtech",
        services: ["Sensor Grid", "Precision Irrigation", "Crop Consultant"],
        image: "https://images.unsplash.com/photo-1472214103451-9374bd1c798e?w=400&h=300&auto=format&fit=crop",
        description: "Premium research facility with advanced sensor networks and precision agriculture tools.",
        features: ["Sensor Network", "Precision Tools", "Expert Consultants", "Data Analytics"],
        rating: 4.9,
        reviews: 31
    },
    {
        id: 5,
        name: "High Ridge Ranch",
        location: "Lubbock, TX",
        pricePerDay: 550,
        industry: "mobility",
        services: ["Heavy Machinery", "Dust Control", "Drone Clearance"],
        image: "https://images.unsplash.com/photo-1527847263472-aa5338d178b8?w=400&h=300&auto=format&fit=crop",
        description: "Large open terrain ideal for mobility and robotics testing in challenging conditions.",
        features: ["Open Terrain", "Heavy Equipment", "Dust Testing", "Clear Airspace"],
        rating: 4.4,
        reviews: 15
    },
    {
        id: 6,
        name: "Echo Valley Co-op",
        location: "Athens, GA",
        pricePerDay: 460,
        industry: "agtech",
        services: ["Tractors", "Operator", "Access to Students"],
        image: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=400&h=300&auto=format&fit=crop",
        description: "University-affiliated testing ground with access to research students and equipment.",
        features: ["University Access", "Student Support", "Research Facilities", "Academic Network"],
        rating: 4.5,
        reviews: 22
    },
    {
        id: 7,
        name: "Dakota Plains Test Site",
        location: "Fargo, ND",
        pricePerDay: 610,
        industry: "robotics",
        services: ["Autonomous Tractor Access", "Winter Trials"],
        image: "https://images.unsplash.com/photo-1605000797499-95a51c5269ae?w=400&h=300&auto=format&fit=crop",
        description: "Specialized facility for autonomous vehicle testing with extreme weather capabilities.",
        features: ["Autonomous Testing", "Winter Conditions", "GPS Systems", "Safety Protocols"],
        rating: 4.6,
        reviews: 9
    },
    {
        id: 8,
        name: "Liberty Ag Commons",
        location: "Lincoln, NE",
        pricePerDay: 490,
        industry: "agtech",
        services: ["Seeder", "Real-Time Weather Feed"],
        image: "https://images.unsplash.com/photo-1464226184884-fa280b87c399?w=400&h=300&auto=format&fit=crop",
        description: "Community agricultural space with modern seeding equipment and weather monitoring.",
        features: ["Weather Station", "Seeding Equipment", "Community Support", "Data Sharing"],
        rating: 4.3,
        reviews: 16
    },
    {
        id: 9,
        name: "Redwood AgTech Field",
        location: "Eugene, OR",
        pricePerDay: 875,
        industry: "agtech",
        services: ["Indoor/Outdoor Plots", "Sensor Suite"],
        image: "https://images.unsplash.com/photo-1530836369250-ef72a3f5cda8?w=400&h=300&auto=format&fit=crop",
        description: "Hybrid indoor-outdoor facility perfect for controlled agricultural experiments.",
        features: ["Indoor/Outdoor", "Climate Control", "Advanced Sensors", "Flexible Layouts"],
        rating: 4.8,
        reviews: 27
    },
    {
        id: 10,
        name: "Clearwater Trials",
        location: "Gainesville, FL",
        pricePerDay: 500,
        industry: "climate",
        services: ["Aquaponics Tanks", "Greenhouse", "Lab Access"],
        image: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=400&h=300&auto=format&fit=crop",
        description: "Aquaponics and climate technology testing facility with greenhouse capabilities.",
        features: ["Aquaponics", "Greenhouse", "Lab Facilities", "Climate Testing"],
        rating: 4.7,
        reviews: 19
    },
    {
        id: 11,
        name: "Prairie Edge Robotics Zone",
        location: "Norman, OK",
        pricePerDay: 660,
        industry: "robotics",
        services: ["GPS Grid", "Open Field for Drones"],
        image: "https://images.unsplash.com/photo-1473773508845-188df298d2d1?w=400&h=300&auto=format&fit=crop",
        description: "Dedicated robotics testing zone with precise GPS grid and drone flight areas.",
        features: ["GPS Grid", "Drone Testing", "Open Space", "Navigation Systems"],
        rating: 4.5,
        reviews: 13
    },
    {
        id: 12,
        name: "Rockwell Agrostation",
        location: "Davis, CA",
        pricePerDay: 900,
        industry: "agtech",
        services: ["24/7 Monitoring", "Research Assistants"],
        image: "https://images.unsplash.com/photo-1595854341625-f33ee10dbf94?w=400&h=300&auto=format&fit=crop",
        description: "Premium agricultural research station with round-the-clock monitoring and expert support.",
        features: ["24/7 Support", "Research Staff", "Monitoring Systems", "Premium Service"],
        rating: 4.9,
        reviews: 35
    },
    {
        id: 13,
        name: "Mesa Dryland Trials",
        location: "Tucson, AZ",
        pricePerDay: 440,
        industry: "climate",
        services: ["Irrigation Systems", "Drought-Tolerant Crops"],
        image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400&h=300&auto=format&fit=crop",
        description: "Desert testing facility specializing in drought-resistant agriculture and water conservation.",
        features: ["Desert Climate", "Water Conservation", "Drought Testing", "Solar Access"],
        rating: 4.4,
        reviews: 11
    },
    {
        id: 14,
        name: "Hudson River Microfarm",
        location: "Hudson Valley, NY",
        pricePerDay: 725,
        industry: "agtech",
        services: ["Urban Farm Tech", "Vertical Racks"],
        image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=300&auto=format&fit=crop",
        description: "Urban microfarm facility with vertical growing systems and city-scale testing capabilities.",
        features: ["Urban Setting", "Vertical Farming", "Space Efficient", "Tech Integration"],
        rating: 4.6,
        reviews: 20
    },
    {
        id: 15,
        name: "Bear Creek Ag Station",
        location: "Des Moines, IA",
        pricePerDay: 530,
        industry: "agtech",
        services: ["Tractor", "Operator", "Planting Assistance"],
        image: "https://images.unsplash.com/photo-1560493676-04071c5f467b?w=400&h=300&auto=format&fit=crop",
        description: "Traditional agricultural facility with experienced operators and planting support.",
        features: ["Experienced Staff", "Traditional Methods", "Hands-on Support", "Flexible Timing"],
        rating: 4.3,
        reviews: 14
    }
];