const sitesData = [
    {
        id: 1,
        name: "Willow Creek Ag Lab",
        location: "Modesto, CA",
        pricePerDay: 850,
        industry: "agtech",
        services: ["Tractor", "Operator", "Soil Lab", "Irrigation Tech"],
        image: "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=400&h=300&auto=format&fit=crop",
        description: "State-of-the-art agricultural testing facility with comprehensive soil analysis capabilities.",
        features: ["24/7 Access", "Climate Controlled", "Data Collection", "Expert Support"],
        rating: 4.8,
        reviews: 24
    },
    {
        id: 2,
        name: "Blue Horizon Farms",
        location: "Ames, IA",
        pricePerDay: 720,
        industry: "agtech",
        services: ["Tractor", "Drone Access", "Local Agronomist"],
        image: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=400&h=300&auto=format&fit=crop",
        description: "Expansive farmland perfect for large-scale agricultural technology testing.",
        features: ["Drone Friendly", "Expert Guidance", "Multiple Plots", "Weather Station"],
        rating: 4.6,
        reviews: 18
    },
    {
        id: 3,
        name: "Pine Ridge Ag Station",
        location: "Bozeman, MT",
        pricePerDay: 680,
        industry: "agtech",
        services: ["Livestock", "Fencing", "Data Collection"],
        image: "https://images.unsplash.com/photo-1500937386664-56d1dfef3854?w=400&h=300&auto=format&fit=crop",
        description: "Mountain agricultural station specializing in livestock and pasture management research.",
        features: ["Livestock Access", "Mountain Climate", "Research Facilities", "Safety Equipment"],
        rating: 4.7,
        reviews: 12
    },
    {
        id: 4,
        name: "TerraNova Research Plot",
        location: "Salinas, CA",
        pricePerDay: 1100,
        industry: "agtech",
        services: ["Sensor Grid", "Precision Irrigation", "Crop Consultant"],
        image: "https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=400&h=300&auto=format&fit=crop",
        description: "Premium research facility with advanced sensor networks and precision agriculture tools.",
        features: ["Sensor Network", "Precision Tools", "Expert Consultants", "Data Analytics"],
        rating: 4.9,
        reviews: 31
    },
    {
        id: 5,
        name: "High Ridge Ranch",
        location: "Lubbock, TX",
        pricePerDay: 550,
        industry: "mobility",
        services: ["Heavy Machinery", "Dust Control", "Drone Clearance"],
        image: "https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=400&h=300&auto=format&fit=crop",
        description: "Large open terrain ideal for mobility and robotics testing in challenging conditions.",
        features: ["Open Terrain", "Heavy Equipment", "Dust Testing", "Clear Airspace"],
        rating: 4.4,
        reviews: 15
    },
    {
        id: 6,
        name: "Echo Valley Co-op",
        location: "Athens, GA",
        pricePerDay: 460,
        industry: "agtech",
        services: ["Tractors", "Operator", "Access to Students"],
        image: "https://images.unsplash.com/photo-1472214103451-9374bd1c798e?w=400&h=300&auto=format&fit=crop",
        description: "University-affiliated testing ground with access to research students and equipment.",
        features: ["University Access", "Student Support", "Research Facilities", "Academic Network"],
        rating: 4.5,
        reviews: 22
    },
    {
        id: 7,
        name: "Dakota Plains Test Site",
        location: "Fargo, ND",
        pricePerDay: 610,
        industry: "robotics",
        services: ["Autonomous Tractor Access", "Winter Trials"],
        image: "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=400&h=300&auto=format&fit=crop",
        description: "Specialized facility for autonomous vehicle testing with extreme weather capabilities.",
        features: ["Autonomous Testing", "Winter Conditions", "GPS Systems", "Safety Protocols"],
        rating: 4.6,
        reviews: 9
    },
    {
        id: 8,
        name: "Liberty Ag Commons",
        location: "Lincoln, NE",
        pricePerDay: 490,
        industry: "agtech",
        services: ["Seeder", "Real-Time Weather Feed"],
        image: "https://images.unsplash.com/photo-1560493676-04071c5f467b?w=400&h=300&auto=format&fit=crop",
        description: "Community agricultural space with modern seeding equipment and weather monitoring.",
        features: ["Weather Station", "Seeding Equipment", "Community Support", "Data Sharing"],
        rating: 4.3,
        reviews: 16
    },
    {
        id: 9,
        name: "Redwood AgTech Field",
        location: "Eugene, OR",
        pricePerDay: 875,
        industry: "agtech",
        services: ["Indoor/Outdoor Plots", "Sensor Suite"],
        image: "https://images.unsplash.com/photo-1530836369250-ef72a3f5cda8?w=400&h=300&auto=format&fit=crop",
        description: "Hybrid indoor-outdoor facility perfect for controlled agricultural experiments.",
        features: ["Indoor/Outdoor", "Climate Control", "Advanced Sensors", "Flexible Layouts"],
        rating: 4.8,
        reviews: 27
    },
    {
        id: 10,
        name: "Clearwater Trials",
        location: "Gainesville, FL",
        pricePerDay: 500,
        industry: "climate",
        services: ["Aquaponics Tanks", "Greenhouse", "Lab Access"],
        image: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=400&h=300&auto=format&fit=crop",
        description: "Aquaponics and climate technology testing facility with greenhouse capabilities.",
        features: ["Aquaponics", "Greenhouse", "Lab Facilities", "Climate Testing"],
        rating: 4.7,
        reviews: 19
    },
    {
        id: 11,
        name: "Prairie Edge Robotics Zone",
        location: "Norman, OK",
        pricePerDay: 660,
        industry: "robotics",
        services: ["GPS Grid", "Open Field for Drones"],
        image: "https://images.unsplash.com/photo-1518709268805-4e9042af2176?w=400&h=300&auto=format&fit=crop",
        description: "Dedicated robotics testing zone with precise GPS grid and drone flight areas.",
        features: ["GPS Grid", "Drone Testing", "Open Space", "Navigation Systems"],
        rating: 4.5,
        reviews: 13
    },
    {
        id: 12,
        name: "Rockwell Agrostation",
        location: "Davis, CA",
        pricePerDay: 900,
        industry: "agtech",
        services: ["24/7 Monitoring", "Research Assistants"],
        image: "https://images.unsplash.com/photo-1595854341625-f33ee10dbf94?w=400&h=300&auto=format&fit=crop",
        description: "Premium agricultural research station with round-the-clock monitoring and expert support.",
        features: ["24/7 Support", "Research Staff", "Monitoring Systems", "Premium Service"],
        rating: 4.9,
        reviews: 35
    },
    {
        id: 13,
        name: "Mesa Dryland Trials",
        location: "Tucson, AZ",
        pricePerDay: 440,
        industry: "climate",
        services: ["Irrigation Systems", "Drought-Tolerant Crops"],
        image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400&h=300&auto=format&fit=crop",
        description: "Desert testing facility specializing in drought-resistant agriculture and water conservation.",
        features: ["Desert Climate", "Water Conservation", "Drought Testing", "Solar Access"],
        rating: 4.4,
        reviews: 11
    },
    {
        id: 14,
        name: "Hudson River Microfarm",
        location: "Hudson Valley, NY",
        pricePerDay: 725,
        industry: "agtech",
        services: ["Urban Farm Tech", "Vertical Racks"],
        image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=300&auto=format&fit=crop",
        description: "Urban microfarm facility with vertical growing systems and city-scale testing capabilities.",
        features: ["Urban Setting", "Vertical Farming", "Space Efficient", "Tech Integration"],
        rating: 4.6,
        reviews: 20
    },
    {
        id: 15,
        name: "Bear Creek Ag Station",
        location: "Des Moines, IA",
        pricePerDay: 530,
        industry: "agtech",
        services: ["Tractor", "Operator", "Planting Assistance"],
        image: "https://images.unsplash.com/photo-1464226184884-fa280b87c399?w=400&h=300&auto=format&fit=crop",
        description: "Traditional agricultural facility with experienced operators and planting support.",
        features: ["Experienced Staff", "Traditional Methods", "Hands-on Support", "Flexible Timing"],
        rating: 4.3,
        reviews: 14
    },
    {
        id: 16,
        name: "Cornfield Alpha",
        location: "Iowa City, IA",
        pricePerDay: 550,
        industry: "agtech",
        services: ["Tractor", "Operator", "Crop Lab", "Irrigation System"],
        image: "https://images.unsplash.com/photo-1572635148818-ef6fd45eb394?w=400&h=300&auto=format&fit=crop",
        description: "Advanced agricultural testing facility with comprehensive crop analysis and irrigation capabilities.",
        features: ["Crop Lab", "Irrigation Systems", "Expert Support", "Data Collection"],
        rating: 4.5,
        reviews: 18
    },
    {
        id: 17,
        name: "Sunny Farm Trials",
        location: "Fresno, CA",
        pricePerDay: 600,
        industry: "agtech",
        services: ["Drone Access", "Local Agronomist", "Weather Station"],
        image: "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=400&h=300&auto=format&fit=crop",
        description: "Sunny agricultural facility perfect for crop testing with drone capabilities and weather monitoring.",
        features: ["Drone Friendly", "Weather Monitoring", "Expert Guidance", "Sunny Climate"],
        rating: 4.6,
        reviews: 22
    },
    {
        id: 18,
        name: "Green Valley Ranch",
        location: "Madison, WI",
        pricePerDay: 520,
        industry: "agtech",
        services: ["Tractor", "Operator", "Pest Monitoring", "IoT Sensors"],
        image: "https://images.unsplash.com/photo-1500937386664-56d1dfef3854?w=400&h=300&auto=format&fit=crop",
        description: "Modern ranch facility with integrated IoT sensors and pest monitoring systems.",
        features: ["IoT Integration", "Pest Control", "Smart Sensors", "Experienced Staff"],
        rating: 4.4,
        reviews: 16
    },
    {
        id: 19,
        name: "Delta Soil Lab",
        location: "Greenville, MS",
        pricePerDay: 480,
        industry: "agtech",
        services: ["Soil Testing", "Drone Imaging", "Irrigation"],
        image: "https://images.unsplash.com/photo-1601131690183-c238e4b4bb2c?w=400&h=300&auto=format&fit=crop",
        description: "Delta region facility specializing in soil analysis with drone imaging capabilities.",
        features: ["Soil Analysis", "Drone Technology", "Delta Climate", "Irrigation Access"],
        rating: 4.3,
        reviews: 13
    },
    {
        id: 20,
        name: "Rocky Plains",
        location: "Fort Collins, CO",
        pricePerDay: 500,
        industry: "agtech",
        services: ["Elevation Testing", "Crop Rotation", "Local Experts"],
        image: "https://images.unsplash.com/photo-1605000797499-95a51c5269ae?w=400&h=300&auto=format&fit=crop",
        description: "High-altitude agricultural testing facility perfect for elevation-specific crop research.",
        features: ["High Altitude", "Crop Rotation", "Local Expertise", "Mountain Climate"],
        rating: 4.7,
        reviews: 11
    },
    {
        id: 21,
        name: "Harvest Grove",
        location: "Salem, OR",
        pricePerDay: 510,
        industry: "agtech",
        services: ["Operator", "Irrigation", "Fruit Crop Access"],
        image: "https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=400&h=300&auto=format&fit=crop",
        description: "Orchard facility specializing in fruit crop testing with expert operators.",
        features: ["Fruit Crops", "Orchard Setting", "Irrigation Systems", "Expert Operators"],
        rating: 4.5,
        reviews: 19
    },
    {
        id: 22,
        name: "Flatland Fields",
        location: "Lubbock, TX",
        pricePerDay: 530,
        industry: "agtech",
        services: ["Tractor", "Weather Station", "Soil Analysis"],
        image: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=400&h=300&auto=format&fit=crop",
        description: "Open flatland facility with comprehensive weather monitoring and soil analysis.",
        features: ["Open Terrain", "Weather Station", "Soil Testing", "Flat Geography"],
        rating: 4.4,
        reviews: 15
    },
    {
        id: 23,
        name: "Everglade Farm Test",
        location: "Gainesville, FL",
        pricePerDay: 570,
        industry: "agtech",
        services: ["Wet Soil Trials", "Pest Testing", "Agronomist"],
        image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=300&auto=format&fit=crop",
        description: "Subtropical testing facility specializing in wet soil conditions and pest management.",
        features: ["Wet Soil Testing", "Pest Management", "Subtropical Climate", "Expert Support"],
        rating: 4.6,
        reviews: 17
    },
    {
        id: 24,
        name: "Maple Leaf Acres",
        location: "Burlington, VT",
        pricePerDay: 490,
        industry: "agtech",
        services: ["Cold Climate Crops", "Tractor", "Lab"],
        image: "https://images.unsplash.com/photo-1551632811-561732d1e306?w=400&h=300&auto=format&fit=crop",
        description: "Northern climate facility perfect for cold-weather crop testing and research.",
        features: ["Cold Climate", "Lab Access", "Winter Testing", "Specialized Crops"],
        rating: 4.3,
        reviews: 12
    },
    {
        id: 25,
        name: "Canyon Ridge Trials",
        location: "Tucson, AZ",
        pricePerDay: 610,
        industry: "agtech",
        services: ["Desert Crops", "Irrigation", "Expert Support"],
        image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400&h=300&auto=format&fit=crop",
        description: "Desert canyon facility specializing in arid climate crop research and water management.",
        features: ["Desert Climate", "Water Conservation", "Canyon Setting", "Expert Guidance"],
        rating: 4.5,
        reviews: 14
    },
    {
        id: 26,
        name: "Sunrise Plant Lab",
        location: "Yuma, AZ",
        pricePerDay: 560,
        industry: "agtech",
        services: ["Greenhouse Access", "Irrigation", "Crop Sensor"],
        image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=300&auto=format&fit=crop",
        description: "Advanced plant laboratory with greenhouse facilities and sensor technology.",
        features: ["Greenhouse", "Sensor Technology", "Controlled Environment", "Plant Research"],
        rating: 4.7,
        reviews: 21
    },
    {
        id: 27,
        name: "Wheatstone Range",
        location: "Lincoln, NE",
        pricePerDay: 500,
        industry: "agtech",
        services: ["Wheat Testing", "Machinery", "Local Support"],
        image: "https://images.unsplash.com/photo-1572635148818-ef6fd45eb394?w=400&h=300&auto=format&fit=crop",
        description: "Dedicated wheat testing facility with specialized machinery and local expertise.",
        features: ["Wheat Specialization", "Farm Machinery", "Local Expertise", "Plains Setting"],
        rating: 4.4,
        reviews: 16
    },
    {
        id: 28,
        name: "Golden Prairie Testbed",
        location: "Topeka, KS",
        pricePerDay: 520,
        industry: "agtech",
        services: ["Open Field", "Sensor Rig", "Machinery"],
        image: "https://images.unsplash.com/photo-1464226184884-fa280b87c399?w=400&h=300&auto=format&fit=crop",
        description: "Open prairie testing ground with advanced sensor systems and agricultural machinery.",
        features: ["Open Prairie", "Sensor Systems", "Agricultural Machinery", "Wide Open Space"],
        rating: 4.6,
        reviews: 18
    },
    {
        id: 29,
        name: "Silicon Crops",
        location: "Palo Alto, CA",
        pricePerDay: 580,
        industry: "agtech",
        services: ["Precision Ag Tools", "Sensor Testing", "Drone Hub"],
        image: "https://images.unsplash.com/photo-1581092160562-40aa08e78837?w=400&h=300&auto=format&fit=crop",
        description: "High-tech agricultural facility in Silicon Valley with cutting-edge precision agriculture tools.",
        features: ["Precision Technology", "Drone Operations", "Tech Integration", "Innovation Hub"],
        rating: 4.8,
        reviews: 25
    },
    {
        id: 30,
        name: "River Delta Acres",
        location: "Sacramento, CA",
        pricePerDay: 540,
        industry: "agtech",
        services: ["Irrigation Canal", "Tractor", "Soil Monitoring"],
        image: "https://images.unsplash.com/photo-1495107334309-fcf20504a5ab?w=400&h=300&auto=format&fit=crop",
        description: "Delta region facility with canal irrigation systems and comprehensive soil monitoring.",
        features: ["Canal Irrigation", "Delta Soil", "Water Management", "Soil Monitoring"],
        rating: 4.5,
        reviews: 20
    },
    {
        id: 31,
        name: "Desert Road Proving Ground",
        location: "Barstow, CA",
        pricePerDay: 950,
        industry: "mobility",
        services: ["Off-road testing", "High-temp conditions", "Autonomous Vehicle Track"],
        image: "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=400&h=300&auto=format&fit=crop",
        description: "Extreme desert testing facility for off-road and autonomous vehicle development in high-temperature conditions.",
        features: ["Off-road Terrain", "High Temperature", "Autonomous Testing", "Desert Conditions"],
        rating: 4.7,
        reviews: 23
    },
    {
        id: 32,
        name: "Metro Mobility Loop",
        location: "Detroit, MI",
        pricePerDay: 880,
        industry: "mobility",
        services: ["Urban traffic simulation", "Sensor Grid", "Charging Infrastructure"],
        image: "https://images.unsplash.com/photo-1519501025264-65ba15a82390?w=400&h=300&auto=format&fit=crop",
        description: "Urban mobility testing facility with traffic simulation and EV charging infrastructure.",
        features: ["Urban Environment", "Traffic Simulation", "EV Charging", "Sensor Network"],
        rating: 4.6,
        reviews: 19
    },
    {
        id: 33,
        name: "Rust Belt Mobility Field",
        location: "Cleveland, OH",
        pricePerDay: 790,
        industry: "mobility",
        services: ["EV Charging Network", "Rough Terrain", "Traffic Simulation"],
        image: "https://images.unsplash.com/photo-1518709268805-4e9042af2176?w=400&h=300&auto=format&fit=crop",
        description: "Industrial mobility testing facility with challenging terrain and comprehensive EV infrastructure.",
        features: ["Industrial Setting", "Rough Terrain", "EV Infrastructure", "Traffic Testing"],
        rating: 4.4,
        reviews: 15
    },
    {
        id: 34,
        name: "Coastal Highway Strip",
        location: "Charleston, SC",
        pricePerDay: 730,
        industry: "mobility",
        services: ["Salt Exposure", "Long-Range Highway Testing"],
        image: "https://images.unsplash.com/photo-1449824913935-59a10b8d2000?w=400&h=300&auto=format&fit=crop",
        description: "Coastal testing facility for long-range highway testing with salt exposure conditions.",
        features: ["Coastal Environment", "Salt Exposure", "Highway Testing", "Long Range"],
        rating: 4.5,
        reviews: 17
    },
    {
        id: 35,
        name: "Midwest Logistics Hub",
        location: "Indianapolis, IN",
        pricePerDay: 810,
        industry: "mobility",
        services: ["Heavy Truck Access", "Depot Simulation", "Loading Equipment"],
        image: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=400&h=300&auto=format&fit=crop",
        description: "Logistics testing facility with heavy truck access and depot simulation capabilities.",
        features: ["Heavy Truck Testing", "Logistics Simulation", "Loading Equipment", "Depot Access"],
        rating: 4.6,
        reviews: 21
    },
    {
        id: 36,
        name: "Evergreen Auto Track",
        location: "Tacoma, WA",
        pricePerDay: 920,
        industry: "mobility",
        services: ["Rain Exposure", "Autonomous Navigation", "EV Test Zone"],
        image: "https://images.unsplash.com/photo-1473773508845-188df298d2d1?w=400&h=300&auto=format&fit=crop",
        description: "Pacific Northwest testing facility specializing in wet weather autonomous vehicle testing.",
        features: ["Rain Testing", "Autonomous Systems", "EV Testing", "Wet Conditions"],
        rating: 4.7,
        reviews: 24
    },
    {
        id: 37,
        name: "Prairie Commute Circuit",
        location: "Lincoln, NE",
        pricePerDay: 690,
        industry: "mobility",
        services: ["Public Road Access", "Lane-Marking Diversity"],
        image: "https://images.unsplash.com/photo-1464226184884-fa280b87c399?w=400&h=300&auto=format&fit=crop",
        description: "Prairie testing circuit with diverse lane markings and public road integration.",
        features: ["Public Road Access", "Lane Diversity", "Prairie Setting", "Commute Simulation"],
        rating: 4.3,
        reviews: 14
    },
    {
        id: 38,
        name: "Textron Mobility Lab",
        location: "Austin, TX",
        pricePerDay: 990,
        industry: "mobility",
        services: ["Urban Grid", "Mixed Traffic", "Sensor Suite"],
        image: "https://images.unsplash.com/photo-1473773508845-188df298d2d1?w=400&h=300&auto=format&fit=crop",
        description: "Advanced urban mobility laboratory with mixed traffic scenarios and comprehensive sensor suite.",
        features: ["Urban Grid", "Mixed Traffic", "Advanced Sensors", "Premium Facility"],
        rating: 4.8,
        reviews: 28
    },
    {
        id: 39,
        name: "Maple Ridge EV Route",
        location: "Burlington, VT",
        pricePerDay: 620,
        industry: "mobility",
        services: ["Cold Weather Testing", "Inclines", "Range Trials"],
        image: "https://images.unsplash.com/photo-1551632811-561732d1e306?w=400&h=300&auto=format&fit=crop",
        description: "Cold weather EV testing facility with challenging inclines and range optimization trials.",
        features: ["Cold Weather", "Incline Testing", "EV Range", "Winter Conditions"],
        rating: 4.4,
        reviews: 16
    },
    {
        id: 40,
        name: "Gateway Drive Center",
        location: "St. Louis, MO",
        pricePerDay: 750,
        industry: "mobility",
        services: ["Bridge Access", "Multi-Modal Simulation"],
        image: "https://images.unsplash.com/photo-1527847263472-aa5338d178b8?w=400&h=300&auto=format&fit=crop",
        description: "Multi-modal transportation testing center with bridge access and complex traffic scenarios.",
        features: ["Bridge Testing", "Multi-Modal", "Complex Traffic", "Gateway Location"],
        rating: 4.5,
        reviews: 18
    },
    {
        id: 41,
        name: "Pinehill Urban Track",
        location: "Raleigh, NC",
        pricePerDay: 700,
        industry: "mobility",
        services: ["City Grid Emulation", "Stop-Go Simulation"],
        image: "https://images.unsplash.com/photo-1473773508845-188df298d2d1?w=400&h=300&auto=format&fit=crop",
        description: "Urban testing track with city grid emulation and stop-and-go traffic simulation.",
        features: ["City Grid", "Stop-Go Testing", "Urban Environment", "Traffic Patterns"],
        rating: 4.6,
        reviews: 20
    },
    {
        id: 42,
        name: "Gila Valley Road Lab",
        location: "Phoenix, AZ",
        pricePerDay: 830,
        industry: "mobility",
        services: ["Extreme Heat", "Asphalt Integrity Testbed"],
        image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400&h=300&auto=format&fit=crop",
        description: "Extreme heat testing facility for road surface integrity and high-temperature vehicle performance.",
        features: ["Extreme Heat", "Asphalt Testing", "High Temperature", "Desert Conditions"],
        rating: 4.7,
        reviews: 22
    },
    {
        id: 43,
        name: "Flatland Freight Range",
        location: "Topeka, KS",
        pricePerDay: 670,
        industry: "mobility",
        services: ["Heavy Load Sim", "Trailer Dynamics", "Rural Roads"],
        image: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=400&h=300&auto=format&fit=crop",
        description: "Freight testing facility specializing in heavy load simulation and trailer dynamics.",
        features: ["Heavy Load Testing", "Trailer Dynamics", "Rural Roads", "Freight Simulation"],
        rating: 4.4,
        reviews: 15
    },
    {
        id: 44,
        name: "Rocky Ridge EV Pass",
        location: "Denver, CO",
        pricePerDay: 920,
        industry: "mobility",
        services: ["Mountain Terrain", "Altitude Stress Test"],
        image: "https://images.unsplash.com/photo-1605000797499-95a51c5269ae?w=400&h=300&auto=format&fit=crop",
        description: "High-altitude EV testing facility with challenging mountain terrain and altitude stress testing.",
        features: ["Mountain Terrain", "High Altitude", "EV Testing", "Stress Testing"],
        rating: 4.8,
        reviews: 26
    },
    {
        id: 45,
        name: "Sierra Smart Transit Zone",
        location: "Reno, NV",
        pricePerDay: 890,
        industry: "mobility",
        services: ["Light Rail Crossing", "IoT Traffic Systems"],
        image: "https://images.unsplash.com/photo-1473773508845-188df298d2d1?w=400&h=300&auto=format&fit=crop",
        description: "Smart transit testing zone with light rail integration and IoT traffic management systems.",
        features: ["Light Rail Integration", "IoT Systems", "Smart Transit", "Connected Infrastructure"],
        rating: 4.7,
        reviews: 23
    },
    {
        id: 46,
        name: "SunFlare Solar Field",
        location: "Las Cruces, NM",
        pricePerDay: 720,
        industry: "climate",
        services: ["Solar Arrays", "High Sun Exposure", "Dust Sensors"],
        image: "https://images.unsplash.com/photo-1509391366360-2e959784a276?w=400&h=300&auto=format&fit=crop",
        description: "Solar testing facility with high sun exposure and dust monitoring for renewable energy research.",
        features: ["Solar Testing", "High Sun Exposure", "Dust Monitoring", "Renewable Energy"],
        rating: 4.6,
        reviews: 19
    },
    {
        id: 47,
        name: "Windy Bluffs Test Site",
        location: "Amarillo, TX",
        pricePerDay: 760,
        industry: "climate",
        services: ["Wind Turbines", "High Wind Speeds", "Vibration Monitoring"],
        image: "https://images.unsplash.com/photo-1466611653911-95081537e5b7?w=400&h=300&auto=format&fit=crop",
        description: "Wind energy testing facility with high wind speeds and comprehensive vibration monitoring.",
        features: ["Wind Testing", "High Wind Speeds", "Vibration Analysis", "Wind Turbines"],
        rating: 4.5,
        reviews: 17
    },
    {
        id: 48,
        name: "Carbon Capture Valley",
        location: "Billings, MT",
        pricePerDay: 840,
        industry: "climate",
        services: ["Carbon Sensors", "Biochar Facility", "Lab Access"],
        image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=300&auto=format&fit=crop",
        description: "Carbon capture testing facility with biochar production and advanced carbon monitoring.",
        features: ["Carbon Capture", "Biochar Production", "Lab Facilities", "Environmental Monitoring"],
        rating: 4.7,
        reviews: 21
    },
    {
        id: 49,
        name: "RainField Hydrolab",
        location: "Olympia, WA",
        pricePerDay: 690,
        industry: "climate",
        services: ["Rainwater Systems", "Filtration Units", "Soil Testing"],
        image: "https://images.unsplash.com/photo-1530836369250-ef72a3f5cda8?w=400&h=300&auto=format&fit=crop",
        description: "Rainwater management testing facility with filtration systems and soil analysis capabilities.",
        features: ["Rainwater Management", "Filtration Testing", "Soil Analysis", "Water Systems"],
        rating: 4.4,
        reviews: 16
    },
    {
        id: 50,
        name: "ThermoTech Geosite",
        location: "Boise, ID",
        pricePerDay: 800,
        industry: "climate",
        services: ["Thermal Battery Testing", "Subsurface Heat Sources"],
        image: "https://images.unsplash.com/photo-1605000797499-95a51c5269ae?w=400&h=300&auto=format&fit=crop",
        description: "Geothermal testing facility with thermal battery systems and subsurface heat source access.",
        features: ["Geothermal Testing", "Thermal Batteries", "Heat Sources", "Underground Access"],
        rating: 4.6,
        reviews: 18
    },
    {
        id: 51,
        name: "EverGreen Grid Testbed",
        location: "Portland, OR",
        pricePerDay: 730,
        industry: "climate",
        services: ["Battery Swapping", "Smart Grid", "Weather Station"],
        image: "https://images.unsplash.com/photo-1530836369250-ef72a3f5cda8?w=400&h=300&auto=format&fit=crop",
        description: "Smart grid testing facility with battery swapping technology and comprehensive weather monitoring.",
        features: ["Smart Grid", "Battery Swapping", "Weather Monitoring", "Grid Integration"],
        rating: 4.7,
        reviews: 22
    },
    {
        id: 52,
        name: "Desert Cool Zone",
        location: "Palm Springs, CA",
        pricePerDay: 850,
        industry: "climate",
        services: ["Cool Roof Tech", "Reflective Surfaces", "Heat Resilience"],
        image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400&h=300&auto=format&fit=crop",
        description: "Desert cooling technology facility testing heat resilience and reflective surface technologies.",
        features: ["Cooling Technology", "Heat Resilience", "Reflective Surfaces", "Desert Climate"],
        rating: 4.8,
        reviews: 25
    },
    {
        id: 53,
        name: "Bay Eco Basin",
        location: "Tampa, FL",
        pricePerDay: 780,
        industry: "climate",
        services: ["Wetlands", "Seawall Tech", "Tidal Energy Modules"],
        image: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=400&h=300&auto=format&fit=crop",
        description: "Coastal ecosystem testing facility with wetlands, seawall technology, and tidal energy systems.",
        features: ["Wetland Testing", "Seawall Technology", "Tidal Energy", "Coastal Environment"],
        rating: 4.6,
        reviews: 20
    },
    {
        id: 54,
        name: "Appalachia Carbon Sink",
        location: "Huntington, WV",
        pricePerDay: 770,
        industry: "climate",
        services: ["Afforestation", "Carbon Monitoring", "Drones"],
        image: "https://images.unsplash.com/photo-1500937386664-56d1dfef3854?w=400&h=300&auto=format&fit=crop",
        description: "Forest carbon sink testing facility with afforestation projects and drone monitoring systems.",
        features: ["Forest Testing", "Carbon Monitoring", "Drone Technology", "Afforestation"],
        rating: 4.5,
        reviews: 17
    },
    {
        id: 55,
        name: "SnowCap Melt Station",
        location: "Anchorage, AK",
        pricePerDay: 910,
        industry: "climate",
        services: ["Glacier Melt Simulation", "Cold-Climate Solar"],
        image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=300&auto=format&fit=crop",
        description: "Arctic testing facility for glacier melt simulation and cold-climate solar technology.",
        features: ["Glacier Simulation", "Cold Climate", "Solar Testing", "Arctic Conditions"],
        rating: 4.7,
        reviews: 14
    },
    {
        id: 56,
        name: "Delta Water Trial Site",
        location: "Sacramento, CA",
        pricePerDay: 730,
        industry: "climate",
        services: ["Flood Simulation", "Wetland Reclamation"],
        image: "https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=400&h=300&auto=format&fit=crop",
        description: "Delta water management facility with flood simulation and wetland reclamation capabilities.",
        features: ["Flood Simulation", "Wetland Reclamation", "Water Management", "Delta Environment"],
        rating: 4.4,
        reviews: 16
    },
    {
        id: 57,
        name: "Urban Heat Grid",
        location: "Houston, TX",
        pricePerDay: 760,
        industry: "climate",
        services: ["Heat Island Study", "Smart Cooling Tech"],
        image: "https://images.unsplash.com/photo-1473773508845-188df298d2d1?w=400&h=300&auto=format&fit=crop",
        description: "Urban heat island testing facility with smart cooling technology and thermal monitoring.",
        features: ["Heat Island Research", "Smart Cooling", "Urban Environment", "Thermal Monitoring"],
        rating: 4.6,
        reviews: 19
    },
    {
        id: 58,
        name: "Solarville Smart Roofs",
        location: "Tempe, AZ",
        pricePerDay: 800,
        industry: "climate",
        services: ["Solar Panel Prototypes", "Reflective Paint Testing"],
        image: "https://images.unsplash.com/photo-1509391366360-2e959784a276?w=400&h=300&auto=format&fit=crop",
        description: "Smart roof testing facility with solar panel prototypes and reflective coating technologies.",
        features: ["Smart Roofs", "Solar Prototypes", "Reflective Coatings", "Roof Technology"],
        rating: 4.7,
        reviews: 21
    },
    {
        id: 59,
        name: "BlueSky Air Quality Field",
        location: "Salt Lake City, UT",
        pricePerDay: 690,
        industry: "climate",
        services: ["Air Monitoring Towers", "Pollution Models"],
        image: "https://images.unsplash.com/photo-1605000797499-95a51c5269ae?w=400&h=300&auto=format&fit=crop",
        description: "Air quality monitoring facility with pollution modeling and atmospheric research capabilities.",
        features: ["Air Quality Monitoring", "Pollution Modeling", "Atmospheric Research", "Clean Air"],
        rating: 4.5,
        reviews: 18
    },
    {
        id: 60,
        name: "SwampTech Emissions Lab",
        location: "Baton Rouge, LA",
        pricePerDay: 740,
        industry: "climate",
        services: ["Methane Capture", "Biofiltration"],
        image: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=400&h=300&auto=format&fit=crop",
        description: "Wetland emissions testing facility with methane capture and biofiltration systems.",
        features: ["Methane Capture", "Biofiltration", "Wetland Environment", "Emissions Testing"],
        rating: 4.4,
        reviews: 15
    },
    {
        id: 61,
        name: "AtlasBot Range",
        location: "Yuma, AZ",
        pricePerDay: 790,
        industry: "robotics",
        services: ["Autonomous Robots", "Obstacle Fields", "Sand Testing"],
        image: "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=400&h=300&auto=format&fit=crop",
        description: "Desert robotics testing range with obstacle courses and sand terrain challenges.",
        features: ["Autonomous Robots", "Obstacle Courses", "Sand Terrain", "Desert Testing"],
        rating: 4.6,
        reviews: 20
    },
    {
        id: 62,
        name: "Steelworks Motion Yard",
        location: "Pittsburgh, PA",
        pricePerDay: 850,
        industry: "robotics",
        services: ["Heavy Robotics", "Load Simulation", "Steelwork Terrain"],
        image: "https://images.unsplash.com/photo-1581092160562-40aa08e78837?w=400&h=300&auto=format&fit=crop",
        description: "Industrial robotics facility with heavy load simulation and steelwork terrain challenges.",
        features: ["Heavy Robotics", "Load Testing", "Industrial Terrain", "Steel Environment"],
        rating: 4.7,
        reviews: 23
    },
    {
        id: 63,
        name: "Greenfield Warehouse Test",
        location: "Louisville, KY",
        pricePerDay: 820,
        industry: "robotics",
        services: ["Indoor Navigation", "Pallet Systems", "Conveyor Access"],
        image: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=400&h=300&auto=format&fit=crop",
        description: "Warehouse robotics facility with indoor navigation systems and material handling equipment.",
        features: ["Indoor Navigation", "Warehouse Systems", "Material Handling", "Automated Systems"],
        rating: 4.8,
        reviews: 26
    },
    {
        id: 64,
        name: "BotBarn Agility Zone",
        location: "Lexington, KY",
        pricePerDay: 760,
        industry: "robotics",
        services: ["Livestock Interaction", "Mud Tracks", "Gates"],
        image: "https://images.unsplash.com/photo-1500937386664-56d1dfef3854?w=400&h=300&auto=format&fit=crop",
        description: "Agricultural robotics facility with livestock interaction and challenging terrain obstacles.",
        features: ["Livestock Interaction", "Agility Testing", "Mud Terrain", "Gate Navigation"],
        rating: 4.5,
        reviews: 18
    },
    {
        id: 65,
        name: "MechaDock Assembly Site",
        location: "Mobile, AL",
        pricePerDay: 890,
        industry: "robotics",
        services: ["Dockside Equipment", "Container Manipulation"],
        image: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=400&h=300&auto=format&fit=crop",
        description: "Maritime robotics facility with dockside equipment and container handling systems.",
        features: ["Dockside Operations", "Container Handling", "Maritime Environment", "Heavy Equipment"],
        rating: 4.7,
        reviews: 22
    },
    {
        id: 66,
        name: "AutoStack Robotics Zone",
        location: "Tulsa, OK",
        pricePerDay: 720,
        industry: "robotics",
        services: ["Vertical Climb Robots", "Warehouse Testing"],
        image: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=400&h=300&auto=format&fit=crop",
        description: "Vertical robotics testing facility with climbing challenges and warehouse automation systems.",
        features: ["Vertical Climbing", "Warehouse Automation", "Stack Testing", "Height Challenges"],
        rating: 4.6,
        reviews: 19
    },
    {
        id: 67,
        name: "TechLine Precision Field",
        location: "Rochester, NY",
        pricePerDay: 730,
        industry: "robotics",
        services: ["Assembly Line Robotics", "Fine Motor Sensors"],
        image: "https://images.unsplash.com/photo-1581092160562-40aa08e78837?w=400&h=300&auto=format&fit=crop",
        description: "Precision robotics facility with assembly line simulation and fine motor control testing.",
        features: ["Precision Assembly", "Fine Motor Control", "Sensor Testing", "Manufacturing"],
        rating: 4.8,
        reviews: 25
    },
    {
        id: 68,
        name: "CanyonBot Ridge",
        location: "Moab, UT",
        pricePerDay: 800,
        industry: "robotics",
        services: ["Extreme Terrain Bots", "GPS Accuracy Tests"],
        image: "https://images.unsplash.com/photo-1605000797499-95a51c5269ae?w=400&h=300&auto=format&fit=crop",
        description: "Extreme terrain robotics facility with canyon challenges and GPS accuracy testing.",
        features: ["Extreme Terrain", "Canyon Environment", "GPS Testing", "Navigation Challenges"],
        rating: 4.7,
        reviews: 21
    },
    {
        id: 69,
        name: "Midbay Disaster Sim Lab",
        location: "Norfolk, VA",
        pricePerDay: 870,
        industry: "robotics",
        services: ["Rescue Bots", "Collapsed Structure Mockups"],
        image: "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=400&h=300&auto=format&fit=crop",
        description: "Disaster response robotics facility with rescue simulation and structural collapse scenarios.",
        features: ["Disaster Response", "Rescue Simulation", "Structural Testing", "Emergency Scenarios"],
        rating: 4.9,
        reviews: 28
    },
    {
        id: 70,
        name: "FrostBot Cold Field",
        location: "Minneapolis, MN",
        pricePerDay: 680,
        industry: "robotics",
        services: ["Cold Endurance Bots", "Slippery Surface Navigation"],
        image: "https://images.unsplash.com/photo-1551632811-561732d1e306?w=400&h=300&auto=format&fit=crop",
        description: "Cold weather robotics facility with endurance testing and slippery surface navigation.",
        features: ["Cold Weather Testing", "Endurance Testing", "Slippery Surfaces", "Winter Conditions"],
        rating: 4.4,
        reviews: 16
    },
    {
        id: 71,
        name: "HiveTrack Swarm Zone",
        location: "Provo, UT",
        pricePerDay: 750,
        industry: "robotics",
        services: ["Swarm Robotics", "Multi-Unit Coordination"],
        image: "https://images.unsplash.com/photo-1518709268805-4e9042af2176?w=400&h=300&auto=format&fit=crop",
        description: "Swarm robotics facility with multi-unit coordination and collective behavior testing.",
        features: ["Swarm Testing", "Multi-Unit Systems", "Coordination Testing", "Collective Behavior"],
        rating: 4.6,
        reviews: 20
    },
    {
        id: 72,
        name: "EchoBot Indoor Arena",
        location: "Buffalo, NY",
        pricePerDay: 710,
        industry: "robotics",
        services: ["SLAM Navigation", "Indoor Drone Testbed"],
        image: "https://images.unsplash.com/photo-1473773508845-188df298d2d1?w=400&h=300&auto=format&fit=crop",
        description: "Indoor robotics arena with SLAM navigation testing and drone flight capabilities.",
        features: ["SLAM Navigation", "Indoor Testing", "Drone Operations", "Navigation Systems"],
        rating: 4.5,
        reviews: 18
    },
    {
        id: 73,
        name: "BayPort Robo Testbed",
        location: "Oakland, CA",
        pricePerDay: 830,
        industry: "robotics",
        services: ["Port Robotics", "Cargo Sorting Tech"],
        image: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=400&h=300&auto=format&fit=crop",
        description: "Port robotics facility with cargo handling and automated sorting technology testing.",
        features: ["Port Operations", "Cargo Handling", "Sorting Technology", "Maritime Robotics"],
        rating: 4.7,
        reviews: 23
    },
    {
        id: 74,
        name: "RedClay Terrain Track",
        location: "Macon, GA",
        pricePerDay: 640,
        industry: "robotics",
        services: ["Soil Response Testing", "Robotic Mobility"],
        image: "https://images.unsplash.com/photo-1500937386664-56d1dfef3854?w=400&h=300&auto=format&fit=crop",
        description: "Clay terrain robotics facility with soil response testing and mobility challenges.",
        features: ["Clay Terrain", "Soil Testing", "Mobility Testing", "Terrain Response"],
        rating: 4.3,
        reviews: 15
    },
    {
        id: 75,
        name: "MetroBot Urban Trial",
        location: "Newark, NJ",
        pricePerDay: 780,
        industry: "robotics",
        services: ["Sidewalk Robots", "Crosswalk Timing Sensors"],
        image: "https://images.unsplash.com/photo-1473773508845-188df298d2d1?w=400&h=300&auto=format&fit=crop",
        description: "Urban robotics facility with sidewalk navigation and traffic integration testing.",
        features: ["Urban Navigation", "Sidewalk Testing", "Traffic Integration", "City Environment"],
        rating: 4.6,
        reviews: 21
    }
];